
(function(l, r) { if (l.getElementById('livereloadscript')) return; r = l.createElement('script'); r.async = 1; r.src = '//' + (window.location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1'; r.id = 'livereloadscript'; l.getElementsByTagName('head')[0].appendChild(r) })(window.document);
import { Faceplate } from '/js/core.js';

/* src/Notes.svelte generated by Svelte v3.31.2 */

function add_css() {
	var style = __sv.element("style");
	style.id = "svelte-1vhirc0-style";
	style.textContent = "textarea.svelte-1vhirc0{position:absolute;background:#2c2929;border:none;resize:none;top:60px;left:15px;width:calc(100% - 30px);height:calc(100% - 100px);padding:10px;color:var(--color-light);font-size:12px}";
	__sv.append(document.head, style);
}

// (23:0) <Faceplate title="Notes">
function create_default_slot(ctx) {
	let textarea;
	let mounted;
	let dispose;

	return {
		c() {
			textarea = __sv.element("textarea");
			__sv.attr(textarea, "class", "svelte-1vhirc0");
		},
		m(target, anchor) {
			__sv.insert(target, textarea, anchor);
			__sv.set_input_value(textarea, /*state*/ ctx[0].note);

			if (!mounted) {
				dispose = __sv.listen(textarea, "input", /*textarea_input_handler*/ ctx[1]);
				mounted = true;
			}
		},
		p(ctx, dirty) {
			if (dirty & /*state*/ 1) {
				__sv.set_input_value(textarea, /*state*/ ctx[0].note);
			}
		},
		d(detaching) {
			if (detaching) __sv.detach(textarea);
			mounted = false;
			dispose();
		}
	};
}

function create_fragment(ctx) {
	let faceplate;
	let current;

	faceplate = new Faceplate({
			props: {
				title: "Notes",
				$$slots: { default: [create_default_slot] },
				$$scope: { ctx }
			}
		});

	return {
		c() {
			__sv.create_component(faceplate.$$.fragment);
		},
		m(target, anchor) {
			__sv.mount_component(faceplate, target, anchor);
			current = true;
		},
		p(ctx, [dirty]) {
			const faceplate_changes = {};

			if (dirty & /*$$scope, state*/ 5) {
				faceplate_changes.$$scope = { dirty, ctx };
			}

			faceplate.$set(faceplate_changes);
		},
		i(local) {
			if (current) return;
			__sv.transition_in(faceplate.$$.fragment, local);
			current = true;
		},
		o(local) {
			__sv.transition_out(faceplate.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			__sv.destroy_component(faceplate, detaching);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { state = { note: "" } } = $$props;

	function textarea_input_handler() {
		state.note = this.value;
		$$invalidate(0, state);
	}

	$$self.$$set = $$props => {
		if ("state" in $$props) $$invalidate(0, state = $$props.state);
	};

	return [state, textarea_input_handler];
}

class Notes extends __sv.SvelteComponent {
	constructor(options) {
		super();
		if (!document.getElementById("svelte-1vhirc0-style")) add_css();
		__sv.init(this, options, instance, create_fragment, __sv.safe_not_equal, { state: 0 });
	}
}

export default Notes;
